//! At build time, find every `tree-sitter-*` dependency via `cargo metadata`,
//! locate its `queries/tags.scm`, and copy it into `OUT_DIR`. `src/symbol_index.rs`
//! loads the copies via `include_str!`, giving us a uniform pipeline for every
//! grammar — regardless of whether the upstream crate exposes `TAGS_QUERY` as
//! a public const.
//!
//! We never check these files in. The source of truth is the upstream crate's
//! source tree; this script just hands it to `include_str!`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".into());

    let output = Command::new(&cargo)
        .args(["metadata", "--format-version=1"])
        .output()
        .expect("cargo metadata");
    if !output.status.success() {
        panic!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let meta: serde_json::Value = serde_json::from_slice(&output.stdout).expect("parse metadata");

    let packages = meta["packages"]
        .as_array()
        .expect("metadata.packages is array");

    let mut manifest = String::from("// generated by build.rs — do not edit\n");
    manifest.push_str("pub static GRAMMAR_TAGS: &[(&str, &str)] = &[\n");

    for pkg in packages {
        let name = pkg["name"].as_str().unwrap_or("");
        if !name.starts_with("tree-sitter-") || name == "tree-sitter" {
            continue;
        }
        let Some(manifest_path) = pkg["manifest_path"].as_str() else {
            continue;
        };
        let crate_root = Path::new(manifest_path).parent().unwrap();
        let tags_src = crate_root.join("queries/tags.scm");
        if !tags_src.exists() {
            continue;
        }
        let dst = out_dir.join(format!("{name}-tags.scm"));
        fs::copy(&tags_src, &dst).unwrap_or_else(|e| {
            panic!("copy {tags_src:?} -> {dst:?}: {e}");
        });
        println!("cargo:rerun-if-changed={}", tags_src.display());
        manifest.push_str(&format!(
            "    (\"{name}\", include_str!(\"{name}-tags.scm\")),\n"
        ));
    }
    manifest.push_str("];\n");

    fs::write(out_dir.join("grammar_tags.rs"), manifest).expect("write manifest");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
}
